### bad model login request
POST localhost:5000/api/auth/login
Content-Type: application/json

{
  "Username": "asd"
}

### good model incorrect login
POST localhost:5000/api/auth/login
Content-Type: application/json

{
  "Username": "asd",
  "Password": "aslkdjsalkd"
}

### good model correct login
POST localhost:5000/api/auth/login
Content-Type: application/json

{
  "Username": "someuser",
  "Password": "someuser"
}

### register new user
POST localhost:5000/api/auth/register
Content-Type: application/json

{
  "Username": "someuser",
  "Password": "someuser"
}
